- name: Install docker's repo key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Setup docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present

- name: Install Docker
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Add {{ username }} to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
