- name: Setup gitconfig file
  template:
    src: templates/gitconfig.j2
    dest: /home/{{ lookup('env','USER') }}/.gitconfig
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"

- name: Create git directory
  file:
    path: /home/{{ lookup('env','USER') }}/git
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    state: directory

- name: Clone dotfiles
  git:
    repo: git@github.com:soleblaze/dotfiles.git
    dest: /home/{{ lookup('env','USER') }}/git/dotfiles
    update: no
  become_user: "{{ lookup('env','USER') }}"

- name: Clone scripts
  git:
    repo: git@github.com:soleblaze/scripts.git
    dest: /home/{{ lookup('env','USER') }}/git/scripts
    update: no
  become_user: "{{ lookup('env','USER') }}"

- name: Clone dotfiles-private
  git:
    repo: git@bitbucket.org:soleblaze/dotfiles-private.git
    dest: /home/{{ lookup('env','USER') }}/git/dotfiles-private
    update: no
  become_user: "{{ lookup('env','USER') }}"

- name: Clone dotfiles-encrypted
  git:
    repo: git@bitbucket.org:soleblaze/dotfiles-encrypted.git
    dest: /home/{{ lookup('env','USER') }}/git/dotfiles-encrypted
    update: no
  become_user: "{{ lookup('env','USER') }}"
