- name: Install neovim
  apt:
    name: neovim
    state: present

- name: Install neovim language modules
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python-neovim
      - python3-neovim
      - ruby-neovim

- name: Install ctags
  apt:
    name: exuberant-ctags
    state: present

- name: Create neovim directories
  file:
    path: /home/{{ lookup('env','USER') }}/.config/nvim/{{ item }}
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    state: directory
  with_items:
    - bundle
    - tmp
    - backup
    - colors
    - ftplugin
    - autoload/lightline/colorscheme

- name: Install cobalt2 lightline theme
  get_url:
    url: https://raw.githubusercontent.com/soleblaze/dotfiles/master/nvim/autoload/lightline/colorscheme/cobalt2.vim
    dest: /home/{{ lookup('env','USER') }}/.config/nvim/autoload/lightline/colorscheme/cobalt2.vim
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"

- name: Create init.vim symlink
  file:
    src: /home/{{ lookup('env','USER') }}/git/dotfiles/nvim/init.vim
    dest: /home/{{ lookup('env','USER') }}/.config/nvim/init.vim
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    state: link

- name: Create UltiSnips symlink
  file:
    src: /home/{{ lookup('env','USER') }}/git/dotfiles/nvim/UltiSnips
    dest: /home/{{ lookup('env','USER') }}/.config/nvim/UltiSnips
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    state: link

- name: Download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ lookup('env','USER') }}/.config/nvim/autoload/plug.vim
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
  register: plug

- name: Setup nvim
  command: nvim +PlugInstall +UpdateRemotePlugins +qa
  become_user: "{{ lookup('env','USER') }}"
  when: plug.changed


