- name: Install programming languages/tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - golang
    - nodejs
    - npm
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip

- name: Install generic tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-file
    - dnsutils
    - jq
    - gawk
    - git-crypt
    - libnotify-bin
    - netcat
    - nmap
    - silversearcher-ag
    - strace
    - xsel

- name: Install zeal
  apt:
    name: zeal
    state: present

- name: Install cros-gpu-alpha
  apt:
    name: cros-gpu-alpha
    state: present

- name: Install pet
  apt:
    deb: https://github.com/knqyf263/pet/releases/download/v0.3.5/pet_0.3.5_linux_amd64.deb
