- name: Install programming languages/tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - golang
    - nodejs
    - npm
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip

- name: Install generic tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-file
    - jq
    - gawk
    - git-crypt
    - libnotify-bin
    - silversearcher-ag
    - strace
    - xsel

- name: Install zeal
  apt:
    name: zeal
    state: present

- name: Install cros-gpu-alpha
  apt:
    name: cros-gpu-alpha
    state: present
