- name: Install generic tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-file
    - cros-gpu
    - dnsutils
    - exa
    - exuberant-ctags
    - fd-find
    - jq
    - gawk
    - geeqie
    - git-crypt
    - libnotify-bin
    - netcat
    - nmap
    - openjdk-11-jdk
    - openjdk-11-jre
    - silversearcher-ag
    - strace
    - tldr
    - xsel
    - zeal

- name: Install yq
  get_url:
    url: https://github.com/mikefarah/yq/releases/download/3.2.3/yq_linux_amd64
    dest: /usr/local/bin/yq
    mode: '0555'
    owner: 'root'
    group: 'root'

- name: Install pet
  apt:
    deb: https://github.com/knqyf263/pet/releases/download/v0.3.6/pet_0.3.6_linux_amd64.deb

- name: Install bat for x86_64
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.15.4/bat_0.15.4_amd64.deb
  register: bat

- name: Update bat cache
  command: bat cache --build
  when: bat.changed

- name: Install prettyping for x86_64
  apt:
    name: prettyping

- name: Install delta on x86_64
  apt:
    deb: https://github.com/dandavison/delta/releases/download/0.1.1/git-delta_0.1.1_amd64.deb

- name: Install cobalt2 theme for bat/delta
  git:
    repo: https://github.com/wesbos/cobalt2.git
    dest: /home/{{ lookup('env','USER') }}/.config/bat/themes/cobalt2
    update: no
  become_user: "{{ lookup('env','USER') }}"
