- name: Install weechat
  apt:
    name: weechat
    state: present

- name: Create .weechat directory
  file:
    path: /home/{{ lookup('env','USER') }}/.weechat
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    state: directory

- name: Create symlinks for weechat configuration files
  file:
    src: /home/{{ lookup('env','USER') }}/git/dotfiles-private/weechat/{{ item }}
    dest: /home/{{ lookup('env','USER') }}/.weechat/{{ item }}
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    state: link
  with_items:
    - alias.conf
    - aspell.conf
    - buffers.conf
    - buflist.conf
    - charset.conf
    - exec.conf
    - fifo.conf
    - fset.conf
    - guile.conf
    - iset.conf
    - logger.conf
    - lua.conf
    - perl.conf
    - plugins.conf
    - python.conf
    - relay.conf
    - ruby.conf
    - script.conf
    - sec.conf
    - tcl.conf
    - trigger.conf
    - weechat.conf
    - xfer.conf

- name: Create symlink for irc.conf
  file:
    src: /home/{{ lookup('env','USER') }}/git/dotfiles-encrypted/config/irc.conf
    dest: /home/{{ lookup('env','USER') }}/.weechat/irc.conf
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    state: link
